spring:
  rabbitmq:
    host: 192.168.6.100 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    listener:
      direct:
        prefetch: 1